apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wordpress
      type: front
    name: wordpress
    namespace: default
  spec:
    ports:
    - name: nginx-port
      nodePort: 30004
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    type: NodePort
